config:
  parsers: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
        Name   nginx
        Format regex
        Regex  ^(?<remote>[^ ]*) (?<ident>[^ ]*) (?<auth>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>[A-Z]+) (?<uri>[^ ]+) (?<protocol>[^"]+)" (?<status>\d{3}) (?<bytes>\d+) "(?<referrer>[^"]*)" "(?<agent>[^"]*)" "(?<x_forwarded_for>[^"]*)"
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z

  inputs: |
    [INPUT]
        Name   tail
        Path   /var/log/containers/*.log
        Tag    kube.*
        parser docker

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
    [FILTER]
        Name           rewrite_tag
        Match          kube.*
        Rule           $kubernetes['namespace_name'] ^(.+)$  $1 false
        Emitter_Name   re_emitter
    [FILTER]
        Name   parser
        Match  nginx*
        Key_Name log
        Parser nginx
        Reserve_Data true
 
## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name               es
        Match              nginx
        Host               elasticsearch-es-http.elastic-stack.svc.cluster.local
        tls                On
        Port               9200
        tls.verify         Off
        suppress_type_name On
        HTTP_user          elastic
        HTTP_passwd        2Iiix3Qw99NzoMpXK23l4151
        index              nginx
    [OUTPUT]
        Name               es
        Match              fluentbit
        Host               elasticsearch-es-http.elastic-stack.svc.cluster.local
        tls                On
        Port               9200
        tls.verify         Off
        suppress_type_name On
        HTTP_user          elastic
        HTTP_passwd        2Iiix3Qw99NzoMpXK23l4151
        Index              fluentbit


    [OUTPUT]
        Name               es
        Match              wedwedwcecer
        Host               elasticsearch-es-http.elastic-stack.svc.cluster.local
        tls                On
        Port               9200
        tls.verify         Off
        suppress_type_name On
        HTTP_user          elastic
        HTTP_passwd        2Iiix3Qw99NzoMpXK23l4151
        Index              wedwedwcecer


    [OUTPUT]
        Name               es
        Match              wdfevrtg5tg
        Host               elasticsearch-es-http.elastic-stack.svc.cluster.local
        tls                On
        Port               9200
        tls.verify         Off
        suppress_type_name On
        HTTP_user          elastic
        HTTP_passwd        2Iiix3Qw99NzoMpXK23l4151
        Index              wdfevrtg5tg


    [OUTPUT]
        Name               es
        Match              edewdffref
        Host               elasticsearch-es-http.elastic-stack.svc.cluster.local
        tls                On
        Port               9200
        tls.verify         Off
        suppress_type_name On
        HTTP_user          elastic
        HTTP_passwd        2Iiix3Qw99NzoMpXK23l4151
        Index              edewdffref


    [OUTPUT]
        Name               es
        Match              qwdqwdqwed
        Host               elasticsearch-es-http.elastic-stack.svc.cluster.local
        tls                On
        Port               9200
        tls.verify         Off
        suppress_type_name On
        HTTP_user          elastic
        HTTP_passwd        2Iiix3Qw99NzoMpXK23l4151
        Index              qwdqwdqwed


    [OUTPUT]
        Name               es
        Match              busybox
        Host               elasticsearch-es-http.elastic-stack.svc.cluster.local
        tls                On
        Port               9200
        tls.verify         Off
        suppress_type_name On
        HTTP_user          elastic
        HTTP_passwd        2Iiix3Qw99NzoMpXK23l4151
        Index              busybox


    [OUTPUT]
        Name               es
        Match              nginx-tst5
        Host               elasticsearch-es-http.elastic-stack.svc.cluster.local
        tls                On
        Port               9200
        tls.verify         Off
        suppress_type_name On
        HTTP_user          elastic
        HTTP_passwd        2Iiix3Qw99NzoMpXK23l4151
        Index              nginx-tst5

